name: Lint Code

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: pnpm

      - name: Install package dependencies
        run: pnpm run ${{ inputs.package-name }}:install

      - name: Check Biome
        run: pnpm --dir packages/plugins/${{ inputs.package-name }} run biome:check