name: Plugin Quality Checks

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      has-tests:
        required: false
        type: boolean
        default: false
      has-coverage:
        required: false
        type: boolean
        default: false
      has-lint:
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build Project
    uses: ./.github/workflows/_build.yml
    with:
      package-name: ${{ inputs.package-name }}

  check:
    name: Check Project
    uses: ./.github/workflows/_check.yml
    with:
      package-name: ${{ inputs.package-name }}

  test:
    name: Run Tests
    if: inputs.has-tests
    uses: ./.github/workflows/_test.yml
    with:
      package-name: ${{ inputs.package-name }}
      has-coverage: ${{ inputs.has-coverage }}

  lint:
    name: Lint Code
    if: inputs.has-lint
    uses: ./.github/workflows/_lint.yml
    with:
      package-name: ${{ inputs.package-name }}
