name: Quality Check @oscd-plugins/documentation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/plugins/documentation/**'

jobs:
  quality:
    uses: ./.github/workflows/_quality.yml
    with:
      package-name: documentation
