name: Quality Check @oscd-plugins/communication-explorer

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/plugins/communication-explorer/**'

jobs:
  quality:
    uses: ./.github/workflows/_quality.yml
    with:
      package-name: communication-explorer
