name: Quality Check @oscd-plugins/type-designer

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/plugins/type-designer/**'

jobs:
  quality:
    uses: ./.github/workflows/_quality.yml
    with:
      package-name: type-designer
      has-tests: true
      has-coverage: true
