name: "Plugin: Plugin Store"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/plugins/plugin-store/**"
jobs:
  check:
    uses: "./.github/workflows/check_version.yml"
    with:
      plugin-name: plugin-store

  build:
    needs: [check]
    if: needs.check.outputs.has_change == 'true'
    uses: "./.github/workflows/build.yml"
    with:
      plugin-name: plugin-store
