name: Quality Check @oscd-plugins/auto-doc

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/plugins/auto-doc/**'

jobs:
  build:
    name: Build Project
    uses: ./.github/workflows/_build.yml
    with:
      package-name: auto-doc

  check:
    name: Check Project
    uses: ./.github/workflows/_check.yml
    with:
      package-name: auto-doc

  test:
    name: Run Tests
    uses: ./.github/workflows/_test.yml
    with:
      package-name: auto-doc
