name: Quality Check @oscd-plugins/type-switcher

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/plugins/type-switcher/**'

jobs:
  build:
    name: Build Project
    uses: ./.github/workflows/_build.yml
    with:
      package-name: type-switcher

  check:
    name: Check Project
    uses: ./.github/workflows/_check.yml
    with:
      package-name: type-switcher
