name: "Plugin: Type Designer"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/plugins/type-designer/**"
      - ".github/workflows/plugin_type-designer.yml"

jobs:
  check:
    uses: "./.github/workflows/check_version.yml"
    with:
      plugin-name: type-designer

  test:
    needs: [check]
    if: needs.check.outputs.has_change == 'true'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout oscd-plugins
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        id: pnpm-install

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Type Designer dependencies
        run: pnpm run type-designer:install

      - name: Run unit and integration tests
        run: pnpm -C ./packages/plugins/type-designer run test:run

      - name: Generate coverage report
        run: pnpm -C ./packages/plugins/type-designer run test:coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: type-designer-coverage
          path: packages/plugins/type-designer/coverage/
          if-no-files-found: warn
          retention-days: 30

  build:
    needs: [check, test]
    if: needs.check.outputs.has_change == 'true'
    uses: "./.github/workflows/build.yml"
    with:
      plugin-name: type-designer