name: Quality Check @oscd-plugins/type-distributor

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/plugins/type-distributor/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'packages/core/**'
      - 'packages/ui/**'
      - 'packages/uilib/**'
      - '.github/workflows/**'

jobs:
  build:
    name: Build Project
    uses: ./.github/workflows/_build.yml
    with:
      package-name: type-distributor

  check:
    name: Check Project
    uses: ./.github/workflows/_check.yml
    with:
      package-name: type-distributor

  test:
    name: Run Tests
    uses: ./.github/workflows/_test.yml
    with:
      package-name: type-distributor
      has-coverage: true

  lint:
    name: Lint Code
    uses: ./.github/workflows/_lint.yml
    with:
      package-name: type-distributor